### ISSUE TITLE
error code 500

### ISSUE THREAD

**Issue by gudskomplex** [tictail/gulp-tictail#26]
Hi! 

When setting up the local server i get the error code 500.
I followed the instructions but i cannot make it work and.. Could you break down each step? 
Thank you.

The "theme-example" repo works fine.

**Comment by tiwilliam** [comment]
You are probably having a invalid tag in your theme that's causing it to crash. We should definitely try to improve error handling here.

**Comment by ptz0n** [comment]
Did you manage to resolve the issue? Please paste any insensitive output trace/error log.

**Comment by gudskomplex** [comment]
Sorry, forgot to answer your question!

No there were definitely nothing wrong with the tags since the HTML was copied directly from the Tictail shop. 

I wasn't able to use this repo, instead i used theme-example. Unfortunately my laptop was stolen a couple of weeks ago so i am not able to produce an error log..

**Comment by poluzhnikov** [comment]
Hi there.

Bumped into the same issue. Here is the log on my end:

`TypeError: Cannot read property 'url' of undefined
    at /Users/vitali/LOCALDEV/SUNS/gulp-tictail/node_modules/gulp-tictail/lib/transforms/store.js:58:43
    at arrayMap (/Users/vitali/LOCALDEV/SUNS/gulp-tictail/node_modules/lodash/lodash.js:660:23)
    at Function.map (/Users/vitali/LOCALDEV/SUNS/gulp-tictail/node_modules/lodash/lodash.js:9571:14)
    at Object.transform (/Users/vitali/LOCALDEV/SUNS/gulp-tictail/node_modules/gulp-tictail/lib/transforms/store.js:52:22)
    at /Users/vitali/LOCALDEV/SUNS/gulp-tictail/node_modules/gulp-tictail/lib/middlewares/store.js:11:31
    at _fulfilled (/Users/vitali/LOCALDEV/SUNS/gulp-tictail/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/vitali/LOCALDEV/SUNS/gulp-tictail/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/vitali/LOCALDEV/SUNS/gulp-tictail/node_modules/q/q.js:816:13)
    at /Users/vitali/LOCALDEV/SUNS/gulp-tictail/node_modules/q/q.js:570:49
    at runSingle (/Users/vitali/LOCALDEV/SUNS/gulp-tictail/node_modules/q/q.js:137:13)
    at flush (/Users/vitali/LOCALDEV/SUNS/gulp-tictail/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)`

Any tips would be nice – would be good to get this pice running! Thanks.
